asyncapi/java-spring-template

- README.md
- filters/all.js
- package-lock.json
- package.json
- partials/AmqpConfig.java
- partials/MqttConfig.java
- template/build.gradle
- template/src/main/java/com/asyncapi/model/$$message$$.java
- template/src/main/java/com/asyncapi/model/$$schema$$.java
- template/src/main/resources/application.yml
- fix errors described in #13 
- fix not mentioned problems in Config.java generation for mqtt and amqp
- tested with:
```
servers:
production:
url: api.streetlights.smartylighting.com:{port}
protocol: mqtt
variables:
port:
default: '1883'
enum:
- '1883'
- '8883'
secondProd:
url: api.rabbit.streetlights.smartylighting.com:{port}
protocol: amqp
variables:
port:
default: '5672'
enum:
- '5672'
- '9999'
channels:
smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured:
parameters:
streetlightId:
$ref: '#/components/parameters/streetlightId'
subscribe:
bindings:
amqp:
exchange:
name: my-queue-name
operationId: receiveLightMeasurement
message:
$ref: '#/components/messages/lightMeasured'
smartylighting/streetlights/1/0/action/{streetlightId}/turn/on:
parameters: …
```
> fix: generation for mqtt and amqp

- .gitignore
- .tp-config.json
- filters/all.js
- package-lock.json
- package.json
- use generic filters library
- modify and cleanup of local filters for new testable style
- removed filters that are already in the generator-filters
- I removed the filter that was not used, `print`, you can use in future filter from generator-filters library called `logError`
It looks like a lot of changes, but don't worry, I did not touch the logic. Some filters are removed but only because they are available thanks to the new generator-filter library
See also https://github.com/asyncapi/generator/issues/212
> feat: use new generic filters

- .tp-config.json
- hooks/addApiFile.js
- hooks/fixModelFileNames.js
- hooks/removeNotRelevantParts.js
- migrate to latest generator enabling usage of reusable hooks
- hooks functions refactor to new approach
Test by:
- installing latest generator `npm install @asyncapi/generator -g`
- generate using fork `ag asyncapi.yml https://github.com/derberg/java-spring-template#refactor-hooks -o output --force-write`
What this change gives to template dev:
- write reusable hooks or just use hooks from official asyncapi library to DRY
- https://github.com/asyncapi/generator/blob/master/docs/authoring.md#hooks
- https://github.com/asyncapi/generator-hooks/#using-hooks-library-in-custom-template
See also https://github.com/asyncapi/generator/issues/318
> feat: migrate to latest generator enabling usage of reusable hooks

- README.md
- hooks/packageProcessor.js
- package.json
- partials/AmqpConfig.java
- partials/CommonPublisher.java
- partials/KafkaConfig.java
- partials/KafkaPublisher.java
- partials/MqttConfig.java
- template/build.gradle
- template/src/main/java/com/asyncapi/Application.java
- template/src/main/java/com/asyncapi/infrastructure/Config.java
- template/src/main/java/com/asyncapi/model/$$message$$.java
- template/src/main/java/com/asyncapi/model/$$schema$$.java
- template/src/main/java/com/asyncapi/service/CommandLinePublisher.java
- template/src/main/java/com/asyncapi/service/MessageHandlerService.java
- template/src/main/java/com/asyncapi/service/PublisherService.java
- template/src/test/java/com/asyncapi/ApplicationTests.java
- template/src/test/java/com/asyncapi/SimpleKafkaTest.java
- template/src/test/java/com/asyncapi/TestcontainerKafkaTest.java
- New parameter to set user specific java package name
- Idea of extension from java-spring-cloud-stream template supported
Resolves: #45
> feat: add param to control java package name

- README.md
- package.json
- template/src/main/java/com/asyncapi/model/$$message$$.java
- template/src/main/java/com/asyncapi/model/$$schema$$.java
- by default equals and hashCode are override, it could be disabled by flag
Resolves: #47
> feat: add generation of equals and hashCode to the model

- hooks/05_packageProcessor.js
- package-lock.json
- package.json
- bug description in #65 
- tested with:
- `-p javaPackage=com.test`
- `-p javaPackage=org.test`
- `-p javaPackage=com.asyncapi.test`
Resolves #65
> fix: generation broken if javaPackage param starts with com

- filters/all.js
- template/src/main/java/com/asyncapi/model/$$message$$.java
- template/src/main/java/com/asyncapi/model/$$objectSchema$$.java
Add support of `allOf` definition for schema model. Implementation made as aggregation of types.
Tested with 
```
asyncapi: '2.0.0'
info:
title: allOf example
version: '1.0.0'
channels:
test:
publish:
message:
$ref: '#/components/messages/testMessages'
subscribe:
message:
$ref: '#/components/messages/testMessages2'
components:
messages:
testMessages:
payload:
allOf: # allOf in payload schema
- $ref: "#/components/schemas/objectWithKey"
- $ref: "#/components/schemas/objectWithKey2"
testMessages2:
payload:
allOf: # allOf in payload schema
- $ref: "#/components/schemas/objectWithKey"
- type: string
schemas:
objectWithKey:
type: object
properties:
key:
allOf:
- $ref: "#/components/schemas/objectWithKey3"
- $ref: "#/components/schemas/objectWithKey2"
objectWithKey2:
type: …
```
> feat: add allOf support

- filters/all.js
`format: time` and `format: date-time` of `type: string` has time zone.
Now `OffsetTime` and `OffsetDateTime` classes are used to present these formats in generated model.
Resolves: #95
> fix: support time zones for json time formats 

- filters/all.js
- template/src/main/java/com/asyncapi/model/$$message$$.java
- template/src/main/java/com/asyncapi/model/$$objectSchema$$.java
- array `[]` replaced with `List` 
- more correct generation when `items:` has `type: object`
Resolves: #94
> feat: replace array with List, add type object processing

- filters/all.js
- filter out properly null objects in oneOF and anyOf
Fixes #108
> fix: filter out properly null objects in oneOf and anyOf

- README.md
- package.json
- partials/KafkaConfig.java
This sets the property of adding `ADD_TYPE_INFO_HEADERS` to true for Kafka. 
Currently, it is set to false, Causing the producer to not add headers, and then the corresponding consumer is not able to do the type conversion. 
the property being false, cause the next property i.e 
```
props.put(JsonSerializer.TYPE_MAPPINGS,
```
of no use, as it's not able to add the headers. 
This fixes the first part of the issue: https://github.com/asyncapi/java-spring-template/issues/137
Resolves #137
> feat: set ADD_TYPE_INFO_HEADERS to true and control it with new addTypeInfoHeader param

- filters/all.js
- template/src/main/java/com/asyncapi/model/$$objectSchema$$.java
when having a regex with \\ in pattern the openapi removes it from it.
For example having in the yaml:
```yaml
time:
type: "string"
pattern: "^\\d\\d:\\d\\d$"
```
will result in the java code to:
```java
@JsonProperty("time")@NotNull@Pattern(regexp="^\d\d:\d\d$")
public String getTime() {
return time;
}
```
but should be:
```java
@JsonProperty("time")@NotNull@Pattern(regexp="^\\d\\d:\\d\\d$")
public String getTime() {
return time;
}
```
Resolves #122
> fix: remove \ from \\ in regex patterns for @Pattern annotation

- filters/all.js
- tests/__snapshots__/additional-formats.test.js.snap
- tests/additional-formats.test.js
- tests/mocks/additional-type-formats.yml
- add support of additional data types -https://www.asyncapi.com/docs/specifications/v2.2.0#dataTypeFormat
- add new test api example
Resolves #204
> feat: add support of additional data type formats

- hooks/98_userHelp.js
Many times users faced problem with `AnonymousSchema` model classes. This happens because some `schemas` element defined as sub-object (inside `allOf`, `items` e.t.c.)  and parser couldn't provide any significant name for them and so class name couldn't be defined.
This behavior is not directly problem of parser or template, but rather of user's AsyncAPI itself.
So, I decided to add info message with description how to discard  `AnonymousSchema` classes if generation result contains them.
See also #203 #131 #78
> feat: add help message about AnonymousSchema generated classes

- README.md
- package.json
- template/src/main/resources/application.yml
- A new parameter `mqttClientId` with a default value `guest` was added to `package.json`.
- The order in which the value is prioritized is - parameterValue > asyncApiValue > defaultValue
Resolves #293
> feat: added mqttClientId parameter with a defualt value

- README.md
- hooks/06_chooseMavenOrGradle.js
- package.json
- template/pom.xml
- tests/__snapshots__/parameters.test.js.snap
- tests/parameters.test.js
- Add generation of pom.xml (Maven build file), to enable generation template parameter `maven=true` must be set.
Resolves: #268
> feat: add pom.xml generation

- .asyncapi-tool
Removed Java as a language form asyncapi-tool file
Followup for https://github.com/asyncapi/java-spring-template/pull/339
> chore: update .asyncapi-tool

- README.md
- filters/all.js
- partials/AmqpConfig.java
- partials/AmqpPublisher.java
- partials/AmqpPublisherImpl.java
- partials/CommonPublisher.java
- partials/CommonPublisherImpl.java
- partials/KafkaConfig.java
- partials/KafkaPublisher.java
- partials/KafkaPublisherImpl.java
- partials/MqttConfig.java
- template/src/main/java/com/asyncapi/model/$$parameter$$.java
- template/src/main/java/com/asyncapi/service/CommandLinePublisher.java
- template/src/main/java/com/asyncapi/service/MessageHandlerService.java
- template/src/main/java/com/asyncapi/service/PublisherService.java
- template/src/main/java/com/asyncapi/service/PublisherServiceImpl.java
- template/src/main/resources/application.yml
- template/src/test/java/com/asyncapi/SimpleKafkaTest.java
- template/src/test/java/com/asyncapi/TestcontainerKafkaTest.java
- template/src/test/java/com/asyncapi/TestcontainerMqttTest.java
- tests/__snapshots__/kafka.test.js.snap
- tests/__snapshots__/mqtt.test.js.snap
- tests/__snapshots__/oneOf.test.js.snap
- tests/__snapshots__/parameters.test.js.snap
- tests/kafka.test.js
- tests/mocks/amqp.yml
- tests/mocks/kafka-with-parameters.yml
- tests/mocks/mqtt.yml
- tests/mqtt.test.js
details in #345
General support:
Arbitrary methods:
Resolves #345
Resolves #358
> feat: add support for channel parameters

- template/src/main/java/com/asyncapi/model/$$objectSchema$$.java
- tests/__snapshots__/map-format.test.js.snap
- tests/map-format.test.js
- tests/mocks/map-format.yml
- If schema object has no properties it's hashCode and equals methods will rely on `super` 
Fixes #336
> fix: empty object generation

- template/src/main/java/com/asyncapi/model/$$objectSchema$$.java
- tests/__snapshots__/additional-formats.test.js.snap
- tests/mocks/additional-type-formats.yml
See #418 for details.
Resolves #418
> feat: mark deprecated properties with @Deprecated
